default:exit_01 exit_02 sema_01 sema_02 sema_03 sema_04 sema_05  mutex_01 mutex_02 mutex_03 mutex_04 mutex_05 cv_01 cv_02 cv_03 cv_04 atomic_01 atomic_02 atomic_03
 

exit_01: exit_01.c
	gcc exit_01.c -o exit_01

exit_02: exit_02.c
	gcc exit_02.c -o exit_02

sema_01: sema_01.c
	gcc sema_01.c -o sema_01

sema_02: sema_02.c
	gcc sema_02.c -o sema_02

sema_03: sema_03.c
	gcc sema_03.c -o sema_03

sema_04: sema_04.c
	gcc sema_04.c -o sema_04

sema_05: sema_05.c
	gcc sema_04.c -o sema_04

mutex_01: mutex_01.c
	gcc mutex_01.c -o mutex_01

mutex_02: mutex_02.c
	gcc mutex_02.c -o mutex_02

mutex_03: mutex_03.c
	gcc mutex_03.c -o mutex_03

mutex_04: mutex_04.c
	gcc mutex_04.c -o mutex_04

mutex_05: mutex_05.c
	gcc mutex_05.c -o mutex_05

cv_01: cv_01.c
	gcc cv_01.c -o cv_01

cv_02: cv_02.c
	gcc cv_02.c -o cv_02

cv_03: cv_03.c
	gcc cv_03.c -o cv_03

cv_04: cv_04.c
	gcc cv_04.c -o cv_04

atomic_01: atomic_01.c
	gcc atomic_01.c -o atomic_01

atomic_02: atomic_02.c
	gcc atomic_02.c -o atomic_02

atomic_03: atomic_03.c
	gcc atomic_03.c -o atomic_03 -latomic -g

clean:
	rm exit_01 exit_02 sema_01 sema_02 sema_03 sema_04 sema_05  mutex_01 mutex_02 mutex_03 mutex_04 mutex_05 cv_01 cv_02 cv_03 cv_04 atomic_01 atomic_02 atomic_03
