default: 1 2 3 4 5 6 7

1: 1.c
	gcc 1.c -o 1

2: 2.c
	gcc 2.c -o 2

3: 3.c
	gcc 3.c -o 3

4: 4.c
	gcc 4.c -o 4

5: 5.c
	gcc 5.c -o 5

6: 6.c
	gcc 6.c -o 6

7: 7.c
	gcc 7.c -o 7

clean:
	rm 1 2 3 4 5 6 7
